#if CODE_ANALYSIS
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "TryReleaseLock", Scope = "member", Target = "CorLib.Reactive.Concurrency.EventLoopSchedulerSlim.#Loop()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "CorLib.Reactive.ObservableExtensions.#Using`1(System.IObservable`1<!!0>,System.IDisposable[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "CorLib.Internal.AsyncResult`1.#.ctor(System.AsyncCallback,System.Object,System.Boolean,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ("Microsoft.Naming", "CA1714:FlagsEnumsShouldHavePluralNames", Scope = "type", Target = "CorLib.Reactive.Concurrency.CancellationCheckMode")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "corlib")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "corlib")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cor", Scope = "namespace", Target = "CorLib.Threading")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cor", Scope = "namespace", Target = "CorLib.Reactive.Concurrency")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cor", Scope = "namespace", Target = "CorLib.Reactive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cor", Scope = "namespace", Target = "CorLib.Diagnostics")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cor", Scope = "namespace", Target = "CorLib.Collections.Generic")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cor", Scope = "namespace", Target = "CorLib.Collections.Concurrent")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage ("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Cor", Scope = "namespace", Target = "CorLib")]
#endif
